# Neuro-Bird Configuration
# Streamlined configuration with only actively used parameters

# Vision Module Configuration
vision:
  # Screen capture settings
  screen_capture:
    region:
      top: 275
      left: 520
      width: 400
      height: 700
    fps_target: 60
    
  # OCR settings
  ocr:
    languages: ["en"]
    gpu: true
    verbose: false
    confidence_threshold: 0.3
    text_threshold: 0.3
    width_threshold: 0.5
    height_threshold: 0.5
    min_size: 5
    
  # Score detection
  score_detection:
    region_height: 100
    region_width: 120
    start_y_offset: 100
    start_x_offset: 0  # -1 for center, or specific pixel value from left
    center_indicator: -1  # Special value to indicate center positioning
    scale_factor: 3
    interpolation: "LINEAR" # also can use LANCZOS4, CUBIC and NEAREST
    score_range:
      min: 0
      max: 50
    pattern: "score\\s*:?\\s*(\\d+)"
    regex_group: 1  # Which regex group contains the score number
    
  # UI/Display settings
  display:
    window_title: "Flappy Bird Score Detection"
    show_fps: true
    show_score: true
    show_ocr_time: true
    
    # Text properties
    font_face: "FONT_HERSHEY_SIMPLEX" # OpenCV font
    font_sizes:
      small: 0.4
      medium: 0.5
      large: 0.8
    font_thickness: 1
    large_font_thickness: 2
    
    # Colors (BGR format)
    colors:
      green: [0, 255, 0]
      red: [0, 0, 255] 
      yellow: [0, 255, 255]
      white: [255, 255, 255]
      
    # Text positions
    text_positions:
      fps_label: [10, 25]
      fps_value: [55, 25]
      score_label: [10, 50]
      score_value: [70, 50]
      ocr_time_label: [235, 25]
      ocr_time_value: [325, 25]
      
    # Rectangle properties
    rectangle_thickness: 2
    score_label_offset: [0, 15]
    
    # Default values and thresholds
    defaults:
      invalid_score: 0
      initial_confidence: 0
      detail_level: 1
      fps_target_fallback: 60
      
    # Formatting settings
    formatting:
      decimal_places_fps: 1  # For FPS display precision
      decimal_places_time: 1  # For timing display precision
      
    # Test/Demo settings
    test_settings:
      frame_increment: 1
      ms_conversion_factor: 1000
      recent_times_average: 10
      ocr_interval: 60  # Run OCR every N frames (lower = more frequent)
      quit_key: 'q'
      key_wait_ms: 1
      key_mask: 0xFF

# Utilities Configuration
utils:
  # Logging settings
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file_output: true
    console_output: true
    log_dir: "logs"
    max_log_size_mb: 10
    backup_count: 5
